apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # these labels are deployments related lables
  labels:
    component: backend
    project: expense 
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: backend
      project: expense 
      tier: app
      # pod definition
  template:
    metadata:
      labels:
        component: backend
        project: expense 
        tier: app
    spec:
      containers:
      - name: nginx
        image: gumma4545/backend:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: backend