apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    component: backend
    project: expense 
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service-port
    targetPort: 8080  # target-port